version: '3'

services:

  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=database
    volumes:
      - mysql-data:/var/lib/mysql

  api:
    image: api:latest
    ports:
      - 3333:3333
    build:
      dockerfile: ./api/Dockerfile
      context: ./api
    depends_on:
      - db
    command: >
      sh -c "adonis migration:run &&
             npm start"

  front:
    image: front:latest
    ports:
      - 80:80
    build:
      dockerfile: ./front/Dockerfile
      context: ./front

volumes:
  mysql-data:
    driver: local