apiVersion: v1
kind: Namespace
metadata:
  name: %JOB_NAME%-ns
  labels: 
    name: %JOB_NAME%-ns

---

apiVersion: v1
data:
  .dockerconfigjson: %ECR_CRED%
kind: Secret
metadata:
  name: %JOB_NAME%-ecr-cred
  namespace: %JOB_NAME%-ns
type: kubernetes.io/dockerconfigjson

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: %JOB_NAME%-mysql-configmap
  namespace: %JOB_NAME%-ns
data:
  db_host: %JOB_NAME%-mysql-service.%JOB_NAME%-ns

---

apiVersion: v1
kind: Secret
metadata:
  name: %JOB_NAME%-mysql-secret
  namespace: %JOB_NAME%-ns
type: Opaque
data:
  username: dXNlcgo= # base64 = user
  password: cGFzc3dvcmQK # base64 = password
  root_password: YWRtaW4K # base64 = admin

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
     name: %JOB_NAME%-mysql-pvc
     namespace: %JOB_NAME%-ns
spec:
     accessModes:
     - ReadWriteOnce
     volumeMode: Filesystem
     resources:
       requests:
         storage: 1Gi
     storageClassName: default-storage-class

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: %JOB_NAME%-mysql
  namespace: %JOB_NAME%-ns
  labels:
    app: %JOB_NAME%-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: %JOB_NAME%-mysql
  template:
    metadata:
      labels:
        app: %JOB_NAME%-mysql
    spec:
      containers:
      - name: %JOB_NAME%-mysql
        image: mysql
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: %JOB_NAME%-mysql-data
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: %JOB_NAME%-mysql-secret
              key: root_password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: %JOB_NAME%-mysql-secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: %JOB_NAME%-mysql-secret
              key: password
        - name: MYSQL_DATABASE
          value: my-database
      volumes:
        - name: %JOB_NAME%-mysql-data
          persistentVolumeClaim:
            claimName: %JOB_NAME%-mysql-pvc
              
---

apiVersion: v1
kind: Service
metadata:
  name: %JOB_NAME%-mysql-service
  namespace: %JOB_NAME%-ns
spec:
  selector:
    app: %JOB_NAME%-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: %JOB_NAME%
  namespace: %JOB_NAME%-ns
  labels:
    app: %JOB_NAME%
spec:
  replicas: 1
  selector:
    matchLabels:
      app: %JOB_NAME%
  template:
    metadata:
      labels:
        app: %JOB_NAME%
    spec:
      containers:
      - name: %JOB_NAME%
        image: %REGISTRY%/%JOB_NAME%:%BUILD_NUMBER%
        ports:
        - containerPort: 3333
      imagePullSecrets:
      - name: %JOB_NAME%-ecr-cred

---

apiVersion: v1
kind: Service
metadata:
  name: %JOB_NAME%-service
  namespace: %JOB_NAME%-ns
spec:
  selector:
    app: %JOB_NAME%
  ports:
    - protocol: TCP
      port: 3333
      targetPort: 3333

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: %JOB_NAME%-ingress
  namespace: %JOB_NAME%-ns
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: %JOB_NAME%.luby.ml
      http:
        paths:
          - path: 
            backend:
              serviceName: %JOB_NAME%-service
              servicePort: 3333