version: '3'
services:
  my-app:
    image: my-app
    ports:
      - 3333:3333
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=my-database
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
    driver: local