version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: qualinut
      WORDPRESS_DB_PASSWORD: qualinut2121
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: qualinut
      MYSQL_PASSWORD: qualinut2121
      MYSQL_ROOT_PASSWORD: qualinutadmin2121
    volumes:
      - mysql:/var/lib/mysql

volumes:
  wordpress:
    driver: local
  mysql:
    driver: local

